// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: api/proto/asset_manifest.proto

package manifest

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AtRawManifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Cid           string                 `protobuf:"bytes,4,opt,name=cid,proto3" json:"cid,omitempty"`
	Signature     []byte                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	FormatVersion string                 `protobuf:"bytes,7,opt,name=format_version,json=formatVersion,proto3" json:"format_version,omitempty"` // e.g., "1.0"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AtRawManifest) Reset() {
	*x = AtRawManifest{}
	mi := &file_api_proto_asset_manifest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AtRawManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtRawManifest) ProtoMessage() {}

func (x *AtRawManifest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_asset_manifest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtRawManifest.ProtoReflect.Descriptor instead.
func (*AtRawManifest) Descriptor() ([]byte, []int) {
	return file_api_proto_asset_manifest_proto_rawDescGZIP(), []int{0}
}

func (x *AtRawManifest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *AtRawManifest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *AtRawManifest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *AtRawManifest) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *AtRawManifest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *AtRawManifest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AtRawManifest) GetFormatVersion() string {
	if x != nil {
		return x.FormatVersion
	}
	return ""
}

type AtVecManifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dimensions    int32                  `protobuf:"varint,1,opt,name=dimensions,proto3" json:"dimensions,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Framework     string                 `protobuf:"bytes,3,opt,name=framework,proto3" json:"framework,omitempty"`
	FormatVersion string                 `protobuf:"bytes,4,opt,name=format_version,json=formatVersion,proto3" json:"format_version,omitempty"`
	Cid           string                 `protobuf:"bytes,5,opt,name=cid,proto3" json:"cid,omitempty"`
	Signature     []byte                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Description   string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AtVecManifest) Reset() {
	*x = AtVecManifest{}
	mi := &file_api_proto_asset_manifest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AtVecManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtVecManifest) ProtoMessage() {}

func (x *AtVecManifest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_asset_manifest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtVecManifest.ProtoReflect.Descriptor instead.
func (*AtVecManifest) Descriptor() ([]byte, []int) {
	return file_api_proto_asset_manifest_proto_rawDescGZIP(), []int{1}
}

func (x *AtVecManifest) GetDimensions() int32 {
	if x != nil {
		return x.Dimensions
	}
	return 0
}

func (x *AtVecManifest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AtVecManifest) GetFramework() string {
	if x != nil {
		return x.Framework
	}
	return ""
}

func (x *AtVecManifest) GetFormatVersion() string {
	if x != nil {
		return x.FormatVersion
	}
	return ""
}

func (x *AtVecManifest) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *AtVecManifest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *AtVecManifest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AtVecManifest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_api_proto_asset_manifest_proto protoreflect.FileDescriptor

const file_api_proto_asset_manifest_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/proto/asset_manifest.proto\x12\vAgentNet.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xee\x01\n" +
	"\rAtRawManifest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x10\n" +
	"\x03cid\x18\x04 \x01(\tR\x03cid\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignature\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12%\n" +
	"\x0eformat_version\x18\a \x01(\tR\rformatVersion\"\x97\x02\n" +
	"\rAtVecManifest\x12\x1e\n" +
	"\n" +
	"dimensions\x18\x01 \x01(\x05R\n" +
	"dimensions\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x1c\n" +
	"\tframework\x18\x03 \x01(\tR\tframework\x12%\n" +
	"\x0eformat_version\x18\x04 \x01(\tR\rformatVersion\x12\x10\n" +
	"\x03cid\x18\x05 \x01(\tR\x03cid\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\fR\tsignature\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescriptionB+Z)github.com/stonkagents/agent/pkg/manifestb\x06proto3"

var (
	file_api_proto_asset_manifest_proto_rawDescOnce sync.Once
	file_api_proto_asset_manifest_proto_rawDescData []byte
)

func file_api_proto_asset_manifest_proto_rawDescGZIP() []byte {
	file_api_proto_asset_manifest_proto_rawDescOnce.Do(func() {
		file_api_proto_asset_manifest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_asset_manifest_proto_rawDesc), len(file_api_proto_asset_manifest_proto_rawDesc)))
	})
	return file_api_proto_asset_manifest_proto_rawDescData
}

var file_api_proto_asset_manifest_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_asset_manifest_proto_goTypes = []any{
	(*AtRawManifest)(nil),         // 0: AgentNet.v1.AtRawManifest
	(*AtVecManifest)(nil),         // 1: AgentNet.v1.AtVecManifest
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_api_proto_asset_manifest_proto_depIdxs = []int32{
	2, // 0: AgentNet.v1.AtRawManifest.created_at:type_name -> google.protobuf.Timestamp
	2, // 1: AgentNet.v1.AtVecManifest.created_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_asset_manifest_proto_init() }
func file_api_proto_asset_manifest_proto_init() {
	if File_api_proto_asset_manifest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_asset_manifest_proto_rawDesc), len(file_api_proto_asset_manifest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_asset_manifest_proto_goTypes,
		DependencyIndexes: file_api_proto_asset_manifest_proto_depIdxs,
		MessageInfos:      file_api_proto_asset_manifest_proto_msgTypes,
	}.Build()
	File_api_proto_asset_manifest_proto = out.File
	file_api_proto_asset_manifest_proto_goTypes = nil
	file_api_proto_asset_manifest_proto_depIdxs = nil
}
