// Package: tracker/internal/ratelimit
// Feature: F-013 (Credits & Identity)
// Story: US-013-04 (Rate Limiting)
// Purpose: Velocity-based anomaly detector that auto-blocks abusive IPs and subnets

package ratelimit

import (
	"context"
	"time"

	"github.com/stonkagents/agent/tracker/internal/clock"
	"github.com/stonkagents/agent/tracker/internal/models"
	"github.com/stonkagents/agent/tracker/internal/repository"
)

// Velocity detection thresholds.
const (
	IPBlockThreshold       = 10  // registrations per hour → auto-block IP
	Subnet24BlockThreshold = 50  // registrations per hour → auto-block /24
	Subnet16BlockThreshold = 200 // registrations per hour → auto-block /16
	VelocityBlockDuration  = 24 * time.Hour
)

// VelocityDetectorDeps holds dependencies for VelocityDetector.
type VelocityDetectorDeps struct {
	Limiter Limiter
	Blocks  repository.BlockRepository
	Clock   clock.Clock
}

// VelocityDetector scans rate limit counters and auto-blocks abusive actors.
type VelocityDetector struct {
	limiter Limiter
	blocks  repository.BlockRepository
	clock   clock.Clock
}

// NewVelocityDetector creates a new velocity detector.
func NewVelocityDetector(deps VelocityDetectorDeps) *VelocityDetector {
	return &VelocityDetector{
		limiter: deps.Limiter,
		blocks:  deps.Blocks,
		clock:   deps.Clock,
	}
}

// Scan checks all active rate limit counters and auto-blocks any that exceed velocity thresholds.
// Returns the number of new blocks created.
func (v *VelocityDetector) Scan(ctx context.Context) (int, error) {
	now := v.clock.Now()
	blocked := 0

	// Check IP-level velocity
	ipKeys, err := v.limiter.ListKeys(ctx, "rl:reg:ip:")
	if err != nil {
		return 0, err
	}
	for _, key := range ipKeys {
		count, _ := v.limiter.GetCount(ctx, key, time.Hour)
		if count > IPBlockThreshold {
			ipValue := key[len("rl:reg:ip:"):]
			// Skip if already blocked
			alreadyBlocked, _ := v.blocks.IsBlocked(ctx, "ip", ipValue, now)
			if alreadyBlocked {
				continue
			}
			_ = v.blocks.Insert(ctx, &models.RegistrationBlock{
				BlockType:     "ip",
				BlockValue:    ipValue,
				Reason:        "S-VEL1",
				BlockedAt:     now,
				ExpiresAt:     now.Add(VelocityBlockDuration),
				AutoGenerated: true,
			})
			blocked++
		}
	}

	// Check /24 subnet velocity
	s24Keys, err := v.limiter.ListKeys(ctx, "rl:reg:s24:")
	if err != nil {
		return blocked, err
	}
	for _, key := range s24Keys {
		count, _ := v.limiter.GetCount(ctx, key, time.Hour)
		if count > Subnet24BlockThreshold {
			subnetValue := key[len("rl:reg:s24:"):]
			alreadyBlocked, _ := v.blocks.IsBlocked(ctx, models.BlockTypeSubnet24, subnetValue, now)
			if alreadyBlocked {
				continue
			}
			_ = v.blocks.Insert(ctx, &models.RegistrationBlock{
				BlockType:     models.BlockTypeSubnet24,
				BlockValue:    subnetValue,
				Reason:        "S-LOC1",
				BlockedAt:     now,
				ExpiresAt:     now.Add(VelocityBlockDuration),
				AutoGenerated: true,
			})
			blocked++
		}
	}

	// Check /16 subnet velocity
	s16Keys, err := v.limiter.ListKeys(ctx, "rl:reg:s16:")
	if err != nil {
		return blocked, err
	}
	for _, key := range s16Keys {
		count, _ := v.limiter.GetCount(ctx, key, time.Hour)
		if count > Subnet16BlockThreshold {
			subnetValue := key[len("rl:reg:s16:"):]
			alreadyBlocked, _ := v.blocks.IsBlocked(ctx, models.BlockTypeSubnet16, subnetValue, now)
			if alreadyBlocked {
				continue
			}
			_ = v.blocks.Insert(ctx, &models.RegistrationBlock{
				BlockType:     models.BlockTypeSubnet16,
				BlockValue:    subnetValue,
				Reason:        "S-LOC2",
				BlockedAt:     now,
				ExpiresAt:     now.Add(VelocityBlockDuration),
				AutoGenerated: true,
			})
			blocked++
		}
	}

	return blocked, nil
}
