// Feature: F-010 (P2P Transfer Protocol)
// Story: US-010-05 (Bitswap-like Block Exchange Protocol)
// Purpose: Protocol Buffer wire format for chunk-based file transfers
// Inspired by: IPFS Bitswap protocol, simplified for StonkAgents

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: api/proto/block_exchange.proto

package protov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message is the top-level envelope for all block exchange messages.
// Uses a oneof to support multiple message types over a single stream.
type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Message_BlockRequest
	//	*Message_BlockResponse
	//	*Message_BlockNotFound
	//	*Message_BlockPresence
	//	*Message_WantList
	Payload       isMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_api_proto_block_exchange_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_block_exchange_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_api_proto_block_exchange_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetPayload() isMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Message) GetBlockRequest() *BlockRequest {
	if x != nil {
		if x, ok := x.Payload.(*Message_BlockRequest); ok {
			return x.BlockRequest
		}
	}
	return nil
}

func (x *Message) GetBlockResponse() *BlockResponse {
	if x != nil {
		if x, ok := x.Payload.(*Message_BlockResponse); ok {
			return x.BlockResponse
		}
	}
	return nil
}

func (x *Message) GetBlockNotFound() *BlockNotFound {
	if x != nil {
		if x, ok := x.Payload.(*Message_BlockNotFound); ok {
			return x.BlockNotFound
		}
	}
	return nil
}

func (x *Message) GetBlockPresence() *BlockPresence {
	if x != nil {
		if x, ok := x.Payload.(*Message_BlockPresence); ok {
			return x.BlockPresence
		}
	}
	return nil
}

func (x *Message) GetWantList() *WantList {
	if x != nil {
		if x, ok := x.Payload.(*Message_WantList); ok {
			return x.WantList
		}
	}
	return nil
}

type isMessage_Payload interface {
	isMessage_Payload()
}

type Message_BlockRequest struct {
	BlockRequest *BlockRequest `protobuf:"bytes,1,opt,name=block_request,json=blockRequest,proto3,oneof"`
}

type Message_BlockResponse struct {
	BlockResponse *BlockResponse `protobuf:"bytes,2,opt,name=block_response,json=blockResponse,proto3,oneof"`
}

type Message_BlockNotFound struct {
	BlockNotFound *BlockNotFound `protobuf:"bytes,3,opt,name=block_not_found,json=blockNotFound,proto3,oneof"`
}

type Message_BlockPresence struct {
	BlockPresence *BlockPresence `protobuf:"bytes,4,opt,name=block_presence,json=blockPresence,proto3,oneof"`
}

type Message_WantList struct {
	WantList *WantList `protobuf:"bytes,5,opt,name=want_list,json=wantList,proto3,oneof"`
}

func (*Message_BlockRequest) isMessage_Payload() {}

func (*Message_BlockResponse) isMessage_Payload() {}

func (*Message_BlockNotFound) isMessage_Payload() {}

func (*Message_BlockPresence) isMessage_Payload() {}

func (*Message_WantList) isMessage_Payload() {}

// BlockRequest requests a specific chunk from a peer.
// Sent by downloaders to seeders.
type BlockRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// file_cid is the content identifier of the complete file
	FileCid string `protobuf:"bytes,1,opt,name=file_cid,json=fileCid,proto3" json:"file_cid,omitempty"`
	// chunk_index is the 0-based position of the requested chunk
	ChunkIndex int32 `protobuf:"varint,2,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	// request_id is a unique identifier for this request (for tracking/debugging)
	RequestId string `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// priority indicates request urgency (0=low, 100=high)
	// Used for prioritizing chunk delivery in upload queues
	Priority      int32 `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockRequest) Reset() {
	*x = BlockRequest{}
	mi := &file_api_proto_block_exchange_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockRequest) ProtoMessage() {}

func (x *BlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_block_exchange_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockRequest.ProtoReflect.Descriptor instead.
func (*BlockRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_block_exchange_proto_rawDescGZIP(), []int{1}
}

func (x *BlockRequest) GetFileCid() string {
	if x != nil {
		return x.FileCid
	}
	return ""
}

func (x *BlockRequest) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *BlockRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *BlockRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

// BlockResponse delivers a requested chunk.
// Sent by seeders to downloaders.
type BlockResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// file_cid is the content identifier of the complete file
	FileCid string `protobuf:"bytes,1,opt,name=file_cid,json=fileCid,proto3" json:"file_cid,omitempty"`
	// chunk_index is the 0-based position of this chunk
	ChunkIndex int32 `protobuf:"varint,2,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	// chunk_cid is the content identifier of this specific chunk
	// Receiver must verify this matches the actual data
	ChunkCid string `protobuf:"bytes,3,opt,name=chunk_cid,json=chunkCid,proto3" json:"chunk_cid,omitempty"`
	// data is the raw chunk bytes (max 256KB = 262,144 bytes)
	Data []byte `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	// request_id matches the original BlockRequest for tracking
	RequestId     string `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockResponse) Reset() {
	*x = BlockResponse{}
	mi := &file_api_proto_block_exchange_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockResponse) ProtoMessage() {}

func (x *BlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_block_exchange_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockResponse.ProtoReflect.Descriptor instead.
func (*BlockResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_block_exchange_proto_rawDescGZIP(), []int{2}
}

func (x *BlockResponse) GetFileCid() string {
	if x != nil {
		return x.FileCid
	}
	return ""
}

func (x *BlockResponse) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *BlockResponse) GetChunkCid() string {
	if x != nil {
		return x.ChunkCid
	}
	return ""
}

func (x *BlockResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *BlockResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// BlockNotFound indicates the requested chunk is not available.
// Sent by seeders when they don't have the requested chunk.
type BlockNotFound struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// file_cid is the content identifier of the requested file
	FileCid string `protobuf:"bytes,1,opt,name=file_cid,json=fileCid,proto3" json:"file_cid,omitempty"`
	// chunk_index is the missing chunk position
	ChunkIndex int32 `protobuf:"varint,2,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	// request_id matches the original BlockRequest
	RequestId string `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// reason explains why the block is unavailable (optional)
	Reason        string `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockNotFound) Reset() {
	*x = BlockNotFound{}
	mi := &file_api_proto_block_exchange_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockNotFound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockNotFound) ProtoMessage() {}

func (x *BlockNotFound) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_block_exchange_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockNotFound.ProtoReflect.Descriptor instead.
func (*BlockNotFound) Descriptor() ([]byte, []int) {
	return file_api_proto_block_exchange_proto_rawDescGZIP(), []int{3}
}

func (x *BlockNotFound) GetFileCid() string {
	if x != nil {
		return x.FileCid
	}
	return ""
}

func (x *BlockNotFound) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *BlockNotFound) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *BlockNotFound) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// BlockPresence advertises which chunks a peer has available.
// Sent proactively or in response to WantList queries.
// Helps downloaders make smart decisions about peer selection.
type BlockPresence struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// file_cid is the content identifier of the file
	FileCid string `protobuf:"bytes,1,opt,name=file_cid,json=fileCid,proto3" json:"file_cid,omitempty"`
	// available_chunks is a bitmap of chunk indices this peer has
	// For efficiency, uses run-length encoding: [start, length, start, length, ...]
	// Example: [0, 10, 20, 5] means chunks 0-9 and 20-24 are available
	AvailableChunks []int32 `protobuf:"varint,2,rep,packed,name=available_chunks,json=availableChunks,proto3" json:"available_chunks,omitempty"`
	// total_chunks is the total number of chunks for this file
	TotalChunks int32 `protobuf:"varint,3,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	// is_complete indicates if this peer has all chunks (seeder)
	IsComplete    bool `protobuf:"varint,4,opt,name=is_complete,json=isComplete,proto3" json:"is_complete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockPresence) Reset() {
	*x = BlockPresence{}
	mi := &file_api_proto_block_exchange_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockPresence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockPresence) ProtoMessage() {}

func (x *BlockPresence) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_block_exchange_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockPresence.ProtoReflect.Descriptor instead.
func (*BlockPresence) Descriptor() ([]byte, []int) {
	return file_api_proto_block_exchange_proto_rawDescGZIP(), []int{4}
}

func (x *BlockPresence) GetFileCid() string {
	if x != nil {
		return x.FileCid
	}
	return ""
}

func (x *BlockPresence) GetAvailableChunks() []int32 {
	if x != nil {
		return x.AvailableChunks
	}
	return nil
}

func (x *BlockPresence) GetTotalChunks() int32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *BlockPresence) GetIsComplete() bool {
	if x != nil {
		return x.IsComplete
	}
	return false
}

// WantList declares what chunks a peer wants.
// Sent by downloaders to seeders to express interest.
// Allows seeders to proactively push chunks or prioritize requests.
type WantList struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// file_cid is the content identifier of the desired file
	FileCid string `protobuf:"bytes,1,opt,name=file_cid,json=fileCid,proto3" json:"file_cid,omitempty"`
	// wanted_chunks is a list of chunk indices the peer wants
	WantedChunks []int32 `protobuf:"varint,2,rep,packed,name=wanted_chunks,json=wantedChunks,proto3" json:"wanted_chunks,omitempty"`
	// priority indicates overall interest level (0=low, 100=high)
	Priority      int32 `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WantList) Reset() {
	*x = WantList{}
	mi := &file_api_proto_block_exchange_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WantList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WantList) ProtoMessage() {}

func (x *WantList) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_block_exchange_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WantList.ProtoReflect.Descriptor instead.
func (*WantList) Descriptor() ([]byte, []int) {
	return file_api_proto_block_exchange_proto_rawDescGZIP(), []int{5}
}

func (x *WantList) GetFileCid() string {
	if x != nil {
		return x.FileCid
	}
	return ""
}

func (x *WantList) GetWantedChunks() []int32 {
	if x != nil {
		return x.WantedChunks
	}
	return nil
}

func (x *WantList) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

// FileMetadata describes a complete file's chunking structure.
// Exchanged during initial handshake to agree on chunk layout.
type FileMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// file_cid is the Merkle root of all chunk CIDs
	FileCid string `protobuf:"bytes,1,opt,name=file_cid,json=fileCid,proto3" json:"file_cid,omitempty"`
	// filename is the original filename
	Filename string `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	// total_size is the complete file size in bytes
	TotalSize int64 `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	// total_chunks is the number of 256KB chunks
	TotalChunks int32 `protobuf:"varint,4,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	// chunk_size is typically 262144 (256KB)
	ChunkSize int32 `protobuf:"varint,5,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	// chunk_cids is the ordered list of chunk content identifiers
	// Used to verify file integrity
	ChunkCids []string `protobuf:"bytes,6,rep,name=chunk_cids,json=chunkCids,proto3" json:"chunk_cids,omitempty"`
	// manifest_type is the asset type (e.g., "raw", "vector", "model")
	ManifestType string `protobuf:"bytes,7,opt,name=manifest_type,json=manifestType,proto3" json:"manifest_type,omitempty"`
	// manifest_data is the serialized manifest (protobuf bytes)
	// Contains asset-specific metadata (AtRawManifest or AtVecManifest)
	// Preserved through P2P transfer for asset type reconstruction
	ManifestData  []byte `protobuf:"bytes,8,opt,name=manifest_data,json=manifestData,proto3" json:"manifest_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileMetadata) Reset() {
	*x = FileMetadata{}
	mi := &file_api_proto_block_exchange_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMetadata) ProtoMessage() {}

func (x *FileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_block_exchange_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMetadata.ProtoReflect.Descriptor instead.
func (*FileMetadata) Descriptor() ([]byte, []int) {
	return file_api_proto_block_exchange_proto_rawDescGZIP(), []int{6}
}

func (x *FileMetadata) GetFileCid() string {
	if x != nil {
		return x.FileCid
	}
	return ""
}

func (x *FileMetadata) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileMetadata) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *FileMetadata) GetTotalChunks() int32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *FileMetadata) GetChunkSize() int32 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *FileMetadata) GetChunkCids() []string {
	if x != nil {
		return x.ChunkCids
	}
	return nil
}

func (x *FileMetadata) GetManifestType() string {
	if x != nil {
		return x.ManifestType
	}
	return ""
}

func (x *FileMetadata) GetManifestData() []byte {
	if x != nil {
		return x.ManifestData
	}
	return nil
}

// TransferStats tracks bandwidth and performance metrics.
// Sent periodically for monitoring and reputation scoring.
type TransferStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// peer_id identifies the remote peer
	PeerId string `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	// bytes_sent is the total bytes uploaded to this peer
	BytesSent int64 `protobuf:"varint,2,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	// bytes_received is the total bytes downloaded from this peer
	BytesReceived int64 `protobuf:"varint,3,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`
	// blocks_sent is the number of chunks uploaded
	BlocksSent int32 `protobuf:"varint,4,opt,name=blocks_sent,json=blocksSent,proto3" json:"blocks_sent,omitempty"`
	// blocks_received is the number of chunks downloaded
	BlocksReceived int32 `protobuf:"varint,5,opt,name=blocks_received,json=blocksReceived,proto3" json:"blocks_received,omitempty"`
	// duration_ms is the connection duration in milliseconds
	DurationMs    int64 `protobuf:"varint,6,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferStats) Reset() {
	*x = TransferStats{}
	mi := &file_api_proto_block_exchange_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferStats) ProtoMessage() {}

func (x *TransferStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_block_exchange_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferStats.ProtoReflect.Descriptor instead.
func (*TransferStats) Descriptor() ([]byte, []int) {
	return file_api_proto_block_exchange_proto_rawDescGZIP(), []int{7}
}

func (x *TransferStats) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *TransferStats) GetBytesSent() int64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *TransferStats) GetBytesReceived() int64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

func (x *TransferStats) GetBlocksSent() int32 {
	if x != nil {
		return x.BlocksSent
	}
	return 0
}

func (x *TransferStats) GetBlocksReceived() int32 {
	if x != nil {
		return x.BlocksReceived
	}
	return 0
}

func (x *TransferStats) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

var File_api_proto_block_exchange_proto protoreflect.FileDescriptor

const file_api_proto_block_exchange_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/proto/block_exchange.proto\x12\x14AgentNet.protocol.v1\"\x89\x03\n" +
	"\aMessage\x12I\n" +
	"\rblock_request\x18\x01 \x01(\v2\".AgentNet.protocol.v1.BlockRequestH\x00R\fblockRequest\x12L\n" +
	"\x0eblock_response\x18\x02 \x01(\v2#.AgentNet.protocol.v1.BlockResponseH\x00R\rblockResponse\x12M\n" +
	"\x0fblock_not_found\x18\x03 \x01(\v2#.AgentNet.protocol.v1.BlockNotFoundH\x00R\rblockNotFound\x12L\n" +
	"\x0eblock_presence\x18\x04 \x01(\v2#.AgentNet.protocol.v1.BlockPresenceH\x00R\rblockPresence\x12=\n" +
	"\twant_list\x18\x05 \x01(\v2\x1e.AgentNet.protocol.v1.WantListH\x00R\bwantListB\t\n" +
	"\apayload\"\x85\x01\n" +
	"\fBlockRequest\x12\x19\n" +
	"\bfile_cid\x18\x01 \x01(\tR\afileCid\x12\x1f\n" +
	"\vchunk_index\x18\x02 \x01(\x05R\n" +
	"chunkIndex\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriority\"\x9b\x01\n" +
	"\rBlockResponse\x12\x19\n" +
	"\bfile_cid\x18\x01 \x01(\tR\afileCid\x12\x1f\n" +
	"\vchunk_index\x18\x02 \x01(\x05R\n" +
	"chunkIndex\x12\x1b\n" +
	"\tchunk_cid\x18\x03 \x01(\tR\bchunkCid\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\tR\trequestId\"\x82\x01\n" +
	"\rBlockNotFound\x12\x19\n" +
	"\bfile_cid\x18\x01 \x01(\tR\afileCid\x12\x1f\n" +
	"\vchunk_index\x18\x02 \x01(\x05R\n" +
	"chunkIndex\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\x99\x01\n" +
	"\rBlockPresence\x12\x19\n" +
	"\bfile_cid\x18\x01 \x01(\tR\afileCid\x12)\n" +
	"\x10available_chunks\x18\x02 \x03(\x05R\x0favailableChunks\x12!\n" +
	"\ftotal_chunks\x18\x03 \x01(\x05R\vtotalChunks\x12\x1f\n" +
	"\vis_complete\x18\x04 \x01(\bR\n" +
	"isComplete\"f\n" +
	"\bWantList\x12\x19\n" +
	"\bfile_cid\x18\x01 \x01(\tR\afileCid\x12#\n" +
	"\rwanted_chunks\x18\x02 \x03(\x05R\fwantedChunks\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\"\x8f\x02\n" +
	"\fFileMetadata\x12\x19\n" +
	"\bfile_cid\x18\x01 \x01(\tR\afileCid\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x1d\n" +
	"\n" +
	"total_size\x18\x03 \x01(\x03R\ttotalSize\x12!\n" +
	"\ftotal_chunks\x18\x04 \x01(\x05R\vtotalChunks\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x05 \x01(\x05R\tchunkSize\x12\x1d\n" +
	"\n" +
	"chunk_cids\x18\x06 \x03(\tR\tchunkCids\x12#\n" +
	"\rmanifest_type\x18\a \x01(\tR\fmanifestType\x12#\n" +
	"\rmanifest_data\x18\b \x01(\fR\fmanifestData\"\xd9\x01\n" +
	"\rTransferStats\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\x02 \x01(\x03R\tbytesSent\x12%\n" +
	"\x0ebytes_received\x18\x03 \x01(\x03R\rbytesReceived\x12\x1f\n" +
	"\vblocks_sent\x18\x04 \x01(\x05R\n" +
	"blocksSent\x12'\n" +
	"\x0fblocks_received\x18\x05 \x01(\x05R\x0eblocksReceived\x12\x1f\n" +
	"\vduration_ms\x18\x06 \x01(\x03R\n" +
	"durationMsB3Z1github.com/stonkagents/agent/api/proto/v1;protov1b\x06proto3"

var (
	file_api_proto_block_exchange_proto_rawDescOnce sync.Once
	file_api_proto_block_exchange_proto_rawDescData []byte
)

func file_api_proto_block_exchange_proto_rawDescGZIP() []byte {
	file_api_proto_block_exchange_proto_rawDescOnce.Do(func() {
		file_api_proto_block_exchange_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_block_exchange_proto_rawDesc), len(file_api_proto_block_exchange_proto_rawDesc)))
	})
	return file_api_proto_block_exchange_proto_rawDescData
}

var file_api_proto_block_exchange_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_proto_block_exchange_proto_goTypes = []any{
	(*Message)(nil),       // 0: AgentNet.protocol.v1.Message
	(*BlockRequest)(nil),  // 1: AgentNet.protocol.v1.BlockRequest
	(*BlockResponse)(nil), // 2: AgentNet.protocol.v1.BlockResponse
	(*BlockNotFound)(nil), // 3: AgentNet.protocol.v1.BlockNotFound
	(*BlockPresence)(nil), // 4: AgentNet.protocol.v1.BlockPresence
	(*WantList)(nil),      // 5: AgentNet.protocol.v1.WantList
	(*FileMetadata)(nil),  // 6: AgentNet.protocol.v1.FileMetadata
	(*TransferStats)(nil), // 7: AgentNet.protocol.v1.TransferStats
}
var file_api_proto_block_exchange_proto_depIdxs = []int32{
	1, // 0: AgentNet.protocol.v1.Message.block_request:type_name -> AgentNet.protocol.v1.BlockRequest
	2, // 1: AgentNet.protocol.v1.Message.block_response:type_name -> AgentNet.protocol.v1.BlockResponse
	3, // 2: AgentNet.protocol.v1.Message.block_not_found:type_name -> AgentNet.protocol.v1.BlockNotFound
	4, // 3: AgentNet.protocol.v1.Message.block_presence:type_name -> AgentNet.protocol.v1.BlockPresence
	5, // 4: AgentNet.protocol.v1.Message.want_list:type_name -> AgentNet.protocol.v1.WantList
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_proto_block_exchange_proto_init() }
func file_api_proto_block_exchange_proto_init() {
	if File_api_proto_block_exchange_proto != nil {
		return
	}
	file_api_proto_block_exchange_proto_msgTypes[0].OneofWrappers = []any{
		(*Message_BlockRequest)(nil),
		(*Message_BlockResponse)(nil),
		(*Message_BlockNotFound)(nil),
		(*Message_BlockPresence)(nil),
		(*Message_WantList)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_block_exchange_proto_rawDesc), len(file_api_proto_block_exchange_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_block_exchange_proto_goTypes,
		DependencyIndexes: file_api_proto_block_exchange_proto_depIdxs,
		MessageInfos:      file_api_proto_block_exchange_proto_msgTypes,
	}.Build()
	File_api_proto_block_exchange_proto = out.File
	file_api_proto_block_exchange_proto_goTypes = nil
	file_api_proto_block_exchange_proto_depIdxs = nil
}
