// Package: tracker/internal/repository
// Feature: F-013 (Credits & Identity)
// Story: US-013-04 (Rate Limiting)
// Purpose: Tests for in-memory BlockRepository

package repository

import (
	"context"
	"testing"
	"time"

	"github.com/stonkagents/agent/tracker/internal/models"
)

func newTestBlock(blockType, value string, expiresIn time.Duration) *models.RegistrationBlock {
	return &models.RegistrationBlock{
		ID:            "block-" + blockType + "-" + value,
		BlockType:     blockType,
		BlockValue:    value,
		Reason:        "S-VEL1",
		BlockedAt:     time.Now(),
		ExpiresAt:     time.Now().Add(expiresIn),
		AutoGenerated: true,
	}
}

func TestMemoryBlockRepo_Insert_Success(t *testing.T) {
	repo := NewMemoryBlockRepository()
	ctx := context.Background()

	block := newTestBlock(models.BlockTypeIP, "1.2.3.4", 24*time.Hour)
	err := repo.Insert(ctx, block)
	if err != nil {
		t.Fatalf("Insert() unexpected error: %v", err)
	}

	blocked, err := repo.IsBlocked(ctx, models.BlockTypeIP, "1.2.3.4", time.Now())
	if err != nil {
		t.Fatalf("IsBlocked() unexpected error: %v", err)
	}
	if !blocked {
		t.Error("IsBlocked() = false, want true")
	}
}

func TestMemoryBlockRepo_IsBlocked_NotBlocked(t *testing.T) {
	repo := NewMemoryBlockRepository()
	ctx := context.Background()

	blocked, err := repo.IsBlocked(ctx, models.BlockTypeIP, "1.2.3.4", time.Now())
	if err != nil {
		t.Fatalf("IsBlocked() unexpected error: %v", err)
	}
	if blocked {
		t.Error("IsBlocked() = true, want false (no blocks exist)")
	}
}

func TestMemoryBlockRepo_IsBlocked_Expired(t *testing.T) {
	repo := NewMemoryBlockRepository()
	ctx := context.Background()

	// Block that expired 1 hour ago
	block := newTestBlock(models.BlockTypeIP, "1.2.3.4", -1*time.Hour)
	_ = repo.Insert(ctx, block)

	blocked, _ := repo.IsBlocked(ctx, models.BlockTypeIP, "1.2.3.4", time.Now())
	if blocked {
		t.Error("IsBlocked() = true, want false (block expired)")
	}
}

func TestMemoryBlockRepo_Insert_Upsert(t *testing.T) {
	repo := NewMemoryBlockRepository()
	ctx := context.Background()

	block1 := newTestBlock(models.BlockTypeIP, "1.2.3.4", 1*time.Hour)
	_ = repo.Insert(ctx, block1)

	// Insert same type+value with longer expiry — should upsert
	block2 := newTestBlock(models.BlockTypeIP, "1.2.3.4", 48*time.Hour)
	block2.Reason = "S-LOC1"
	err := repo.Insert(ctx, block2)
	if err != nil {
		t.Fatalf("Insert() upsert unexpected error: %v", err)
	}

	// Should still be blocked (new expiry)
	blocked, _ := repo.IsBlocked(ctx, models.BlockTypeIP, "1.2.3.4", time.Now().Add(2*time.Hour))
	if !blocked {
		t.Error("IsBlocked() after upsert = false, want true (extended expiry)")
	}
}

func TestMemoryBlockRepo_CleanExpired(t *testing.T) {
	repo := NewMemoryBlockRepository()
	ctx := context.Background()

	_ = repo.Insert(ctx, newTestBlock(models.BlockTypeIP, "1.2.3.4", -1*time.Hour))      // expired
	_ = repo.Insert(ctx, newTestBlock(models.BlockTypeIP, "5.6.7.8", 24*time.Hour))      // active
	_ = repo.Insert(ctx, newTestBlock(models.BlockTypeSubnet24, "10.0.1", -2*time.Hour)) // expired

	cleaned, err := repo.CleanExpired(ctx, time.Now())
	if err != nil {
		t.Fatalf("CleanExpired() unexpected error: %v", err)
	}
	if cleaned != 2 {
		t.Errorf("CleanExpired() = %d, want 2", cleaned)
	}
}
