// Package: tracker/internal/repository
// Feature: F-013 (Credits & Identity)
// Story: US-013-01 (Account Registration)
// Purpose: PostgreSQL implementation of BlockRepository for registration rate limiting

package repository

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/stonkagents/agent/tracker/internal/models"
)

// PostgresBlockRepository implements BlockRepository using PostgreSQL.
type PostgresBlockRepository struct {
	pool *pgxpool.Pool
}

// NewPostgresBlockRepository creates a new Postgres block repository.
func NewPostgresBlockRepository(pool *pgxpool.Pool) *PostgresBlockRepository {
	return &PostgresBlockRepository{pool: pool}
}

func (r *PostgresBlockRepository) IsBlocked(ctx context.Context, blockType, blockValue string, now time.Time) (bool, error) {
	var exists bool
	err := r.pool.QueryRow(ctx,
		`SELECT EXISTS(
			SELECT 1 FROM registration_blocks
			WHERE block_type = $1 AND block_value = $2 AND expires_at > $3
		)`, blockType, blockValue, now,
	).Scan(&exists)
	return exists, err
}

func (r *PostgresBlockRepository) Insert(ctx context.Context, block *models.RegistrationBlock) error {
	_, err := r.pool.Exec(ctx,
		`INSERT INTO registration_blocks (id, block_type, block_value, reason, blocked_at, expires_at, auto_generated)
		 VALUES ($1, $2, $3, $4, $5, $6, $7)
		 ON CONFLICT (block_type, block_value)
		 DO UPDATE SET reason = $4, blocked_at = $5, expires_at = $6, auto_generated = $7`,
		block.ID, block.BlockType, block.BlockValue, block.Reason,
		block.BlockedAt, block.ExpiresAt, block.AutoGenerated,
	)
	return err
}

func (r *PostgresBlockRepository) CleanExpired(ctx context.Context, now time.Time) (int, error) {
	cmd, err := r.pool.Exec(ctx,
		`DELETE FROM registration_blocks WHERE expires_at <= $1`, now,
	)
	if err != nil {
		return 0, err
	}
	return int(cmd.RowsAffected()), nil
}
