// Package: tracker/internal/models
// Feature: F-013 (Credits & Identity)
// Story: US-013-01 (Account Registration)
// Purpose: Domain models for accounts, credits, nonces, and registration blocks

package models

import "time"

// AccountStatus constants.
const (
	AccountStatusActive    = "active"
	AccountStatusRecovered = "recovered"
	AccountStatusSuspended = "suspended"
)

// Account represents a registered identity in the credit system.
type Account struct {
	ID        string    `json:"id"`
	PeerID    string    `json:"peer_id"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
}

// CreditBalance holds the credit state for a single account.
type CreditBalance struct {
	AccountID             string     `json:"account_id"`
	FreeBalance           int        `json:"free_balance"`
	PaidBalance           int        `json:"paid_balance"`
	LifetimePurchased     int        `json:"lifetime_purchased"`
	LifetimeSocialGranted int        `json:"lifetime_social_granted"`
	FreeCreditsExpiresAt  *time.Time `json:"free_credits_expires_at,omitempty"`
	// Trial counter for detailed (gpt-5.4) mode. New users get a small allotment
	// of free detailed-mode calls so they can taste the premium model before paying.
	DetailedTrialRemaining int        `json:"detailed_trial_remaining"`
	DetailedTrialExpiresAt *time.Time `json:"detailed_trial_expires_at,omitempty"`
	UpdatedAt              time.Time  `json:"updated_at"`
}

// BalanceType constants for credit transactions.
const (
	BalanceTypeFree  = "free"
	BalanceTypePaid  = "paid"
	BalanceTypeMixed = "mixed"
)

// CreditTransaction is an immutable ledger entry.
type CreditTransaction struct {
	ID          string    `json:"id"`
	AccountID   string    `json:"account_id"`
	Amount      int       `json:"amount"`
	BalanceType string    `json:"balance_type"`
	Reason      string    `json:"reason"`
	RequestID   string    `json:"request_id"`
	CreatedAt   time.Time `json:"created_at"`
}

// RegistrationNonce is a challenge nonce for the registration protocol.
type RegistrationNonce struct {
	ID        string    `json:"id"`
	PeerID    string    `json:"peer_id"`
	Nonce     []byte    `json:"nonce"`
	Consumed  bool      `json:"consumed"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

// BlockType constants.
const (
	BlockTypeIP       = "ip"
	BlockTypeSubnet24 = "subnet_24"
	BlockTypeSubnet16 = "subnet_16"
	BlockTypeASN      = "asn"
)

// RegistrationBlock is a rate-limiting block on an IP/subnet/ASN.
type RegistrationBlock struct {
	ID            string    `json:"id"`
	BlockType     string    `json:"block_type"`
	BlockValue    string    `json:"block_value"`
	Reason        string    `json:"reason"`
	BlockedAt     time.Time `json:"blocked_at"`
	ExpiresAt     time.Time `json:"expires_at"`
	AutoGenerated bool      `json:"auto_generated"`
}
