ALTER TABLE board_reports DROP COLUMN IF EXISTS resolution_note;

ALTER TABLE peers ALTER COLUMN masked_peer_id DROP NOT NULL;
ALTER TABLE peers ALTER COLUMN masked_peer_id DROP DEFAULT;
ALTER TABLE peers ALTER COLUMN region DROP NOT NULL;
ALTER TABLE peers ALTER COLUMN region DROP DEFAULT;
ALTER TABLE peers ALTER COLUMN country DROP NOT NULL;
ALTER TABLE peers ALTER COLUMN country DROP DEFAULT;
